name: Deploy Shiny App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
      RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
      
    steps:
    - uses: actions/checkout@v3

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.1'

    - uses: r-lib/actions/setup-pandoc@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libfontconfig1-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libfreetype6-dev \
          libpng-dev \
          libtiff5-dev \
          libjpeg-dev

    - name: Install R dependencies
      run: |
        install.packages(c(
          'rsconnect',
          'shiny',
          'shinydashboard',
          'shinyjs',
          'DT',
          'googlesheets4',
          'ggplot2',
          'data.table',
          'Rcpp',
          'memoise',
          'pwr',
          'htmltools'
        ), repos = 'https://cloud.r-project.org/')
      shell: Rscript {0}

    - name: Set up shinyapps.io
      run: |
        Rscript -e '
          library(rsconnect)
          rsconnect::setAccountInfo(
            name="areliw",
            token=Sys.getenv("RSCONNECT_TOKEN"),
            secret=Sys.getenv("RSCONNECT_SECRET")
          )'

    - name: Deploy to shinyapps.io
      run: |
        Rscript -e '
          library(rsconnect)
          # ตรวจสอบ package ที่จำเป็น
          required_packages <- c(
            "shiny", "shinydashboard", "shinyjs", "DT",
            "googlesheets4", "ggplot2", "data.table", "Rcpp",
            "memoise", "pwr", "htmltools"
          )
          
          # ติดตั้ง package ที่ขาด
          missing_packages <- required_packages[
            !sapply(required_packages, requireNamespace, quietly = TRUE)
          ]
          if (length(missing_packages) > 0) {
            install.packages(missing_packages, repos = "https://cloud.r-project.org/")
          }
          
          # Deploy app
          rsconnect::deployApp(
            appName = "pbestapp",
            appFiles = c(
              "app.R",
              "ui.R",
              "server.R",
              "global.R",
              "modules",
              "DESCRIPTION"
            ),
            forceUpdate = TRUE,
            launch.browser = FALSE
          )'
