name: Deploy Shiny App

on:
  push:
    branches:
      - main  # ทำงานเมื่อมีการ push ไปที่ branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ${{ runner.tool_cache }}/R
        key: ${{ runner.os }}-R-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: |
      ${{ runner.os }}-R-
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

   - name: Install R packages
  run: |
    Rscript -e 'if (!requireNamespace("shiny", quietly = TRUE)) install.packages("shiny")'
    Rscript -e 'if (!requireNamespace("rsconnect", quietly = TRUE)) install.packages("rsconnect")'

    - name: Deploy Shiny App
      env:
        RSCONNECT_USER: ${{ secrets.RSCONNECT_USER }}
        RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
        RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
      run: |
        Rscript -e 'rsconnect::setAccountInfo(name=Sys.getenv("RSCONNECT_USER"), token=Sys.getenv("RSCONNECT_TOKEN"), secret=Sys.getenv("RSCONNECT_SECRET"))'
        Rscript -e 'rsconnect::deployApp()'
