name: Deploy Shiny App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install R package dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: rsconnect

    - name: Deploy to shinyapps.io
      run: |
        Rscript -e 'rsconnect::setAccountInfo(name="areliw", token="${{ secrets.RSCONNECT_TOKEN }}", secret="${{ secrets.RSCONNECT_SECRET }}")'
        Rscript -e 'rsconnect::deployApp(appName = "pbestapp", forceUpdate = TRUE)'
