name: Deploy to ShinyApps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'  # ใช้เวอร์ชัน R ล่าสุด

      - name: Install rsconnect and additional dependencies
        run: |
          Rscript -e 'install.packages(c("rsconnect", "shiny", "dplyr", "ggplot2", "googlesheets4", "pwr"), repos = "http://cran.us.r-project.org")'

      - name: Deploy app to ShinyApps
        run: |
          Rscript -e 'rsconnect::setAccountInfo(name="areliw", token="81AB9A719963DA294CFF86A9A24C319A", secret="kGpCAN7+r1GexSL6vfcAv25XzX4L69AAUUaMdaha")'
          Rscript -e 'rsconnect::deployApp(appName = "pbestapp")'
