name: Deploy Shiny App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
      RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
      R_LIBS_USER: ${{ github.workspace }}/R/library
      
    steps:
    - uses: actions/checkout@v3

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.1'

    - uses: r-lib/actions/setup-pandoc@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libfontconfig1-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libfreetype6-dev \
          libpng-dev \
          libtiff5-dev \
          libjpeg-dev

    - name: Install R dependencies
      run: |
        Rscript -e '
          if (!require("pak", quietly = TRUE)) {
            install.packages("pak", repos = "https://r-lib.github.io/p/pak/stable/")
          }
          
          packages <- c(
            "rsconnect",
            "shiny",
            "shinydashboard",
            "shinyjs",
            "DT",
            "googlesheets4",
            "ggplot2",
            "data.table",
            "Rcpp",
            "memoise",
            "pwr",
            "htmltools",
            "markdown",
            "rmarkdown"
          )
          
          pak::pkg_install(packages)
          
          # Verify installation
          missing <- packages[!sapply(packages, requireNamespace, quietly = TRUE)]
          if (length(missing) > 0) {
            stop("Missing packages: ", paste(missing, collapse = ", "))
          }
        '

    - name: Deploy to shinyapps.io
      run: |
        Rscript -e '
          library(rsconnect)
          rsconnect::setAccountInfo(
            name="areliw",
            token=Sys.getenv("RSCONNECT_TOKEN"),
            secret=Sys.getenv("RSCONNECT_SECRET")
          )
          
          # Prepare file list
          files_to_deploy <- c(
            "app.R",
            "ui.R",
            "server.R",
            "global.R",
            "DESCRIPTION"
          )
          
          # Add module files
          if (dir.exists("modules")) {
            files_to_deploy <- c(
              files_to_deploy,
              list.files("modules", full.names = TRUE, pattern = "\\.R$")
            )
          }
          
          # Add R utility files
          if (dir.exists("R")) {
            files_to_deploy <- c(
              files_to_deploy,
              list.files("R", full.names = TRUE, pattern = "\\.R$")
            )
          }
          
          # Add www files
          if (dir.exists("www")) {
            files_to_deploy <- c(
              files_to_deploy,
              list.files("www", full.names = TRUE, recursive = TRUE)
            )
          }
          
          # Deploy
          deployApp(
            appFiles = files_to_deploy,
            appName = "pbestapp",
            forceUpdate = TRUE,
            launch.browser = FALSE
          )
        '

    - name: Wait for deployment
      run: sleep 30

    - name: Verify deployment
      run: |
        max_attempts=5
        attempt=1
        while [ $attempt -le $max_attempts ]
        do
          echo "Verification attempt $attempt of $max_attempts"
          if curl -f -s -o /dev/null "https://areliw.shinyapps.io/pbestapp/"; then
            echo "Deployment verified successfully"
            exit 0
          else
            echo "Attempt $attempt failed"
            if [ $attempt -lt $max_attempts ]; then
              sleep 30
            fi
          fi
          attempt=$((attempt + 1))
        done
        echo "Deployment verification failed after $max_attempts attempts"
        exit 1
